# Generated by Django 4.1.3 on 2022-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_company_alter_profile_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='donor',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
