# Generated by Django 4.1.3 on 2022-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_company_alter_profile_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Pick up Date'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Pick up Location'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Pick up Time'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='typeofDonate',
            field=models.CharField(choices=[('P', 'Plastic'), ('p', 'Paper'), ('G', 'Glass Bottles'), ('c', 'Containers')], default='P', max_length=1, verbose_name='Type'),
        ),
    ]
