# Generated by Django 4.1.3 on 2022-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_donate_date_alter_donate_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='date',
            field=models.DateField(max_length=100, verbose_name='Pick up Date'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='time',
            field=models.TimeField(max_length=100, verbose_name='Pick up Time'),
        ),
    ]
