# Generated by Django 4.1.3 on 2022-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_donate_date_alter_donate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='item_image',
            field=models.TextField(default='null', max_length=350, verbose_name='Item Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donate',
            name='typeofDonate',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Glass Bottles', 'Glass Bottles'), ('Containers', 'Containers')], default='Plastic', max_length=100, verbose_name='Type'),
        ),
    ]
