# Generated by Django 4.1.3 on 2022-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_donate_item_image_alter_donate_typeofdonate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
