# Generated by Django 4.1.3 on 2022-12-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_donate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('Donate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.donate')),
            ],
        ),
    ]
